# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 07:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_year', models.CharField(default='', max_length=40, verbose_name='数据名称')),
                ('apply_file', models.FileField(blank=True, null=True, upload_to='static/media/up_data', verbose_name='申请表')),
                ('data_file1', models.FileField(blank=True, null=True, upload_to='static/media/up_data', verbose_name='数据附件1')),
                ('data_file2', models.FileField(blank=True, null=True, upload_to='static/media/up_data', verbose_name='数据附件2')),
                ('data_file3', models.FileField(blank=True, null=True, upload_to='static/media/up_data', verbose_name='数据附件3')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'CSS数据',
                'verbose_name_plural': 'CSS数据',
            },
        ),
        migrations.CreateModel(
            name='UserApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(default='', max_length=1000, verbose_name='申请目的')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='static/media/up_apply', verbose_name='上传申请表')),
                ('result', models.CharField(blank=True, choices=[('未审核', '未审核'), ('审核中', '审核中'), ('审核通过', '审核通过'), ('审核未通过', '审核未通过')], default='未审核', max_length=10, null=True, verbose_name='申请结果')),
                ('apply_date', models.DateTimeField(blank=True, null=True, verbose_name='申请时间')),
                ('check_date', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('data_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skyuser.DataList', verbose_name='数据名称')),
            ],
            options={
                'verbose_name': '数据申请',
                'verbose_name_plural': '数据申请',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='真实姓名')),
                ('sex', models.CharField(choices=[('男', '男'), ('女', '女')], default='', max_length=2, verbose_name='性别')),
                ('idcard', models.CharField(default='', max_length=20, verbose_name='身份证号')),
                ('org', models.CharField(default='', max_length=40, verbose_name='单位')),
                ('subject', models.CharField(default='', max_length=20, verbose_name='专业')),
                ('zhicheng', models.CharField(default='', max_length=20, verbose_name='职称')),
                ('tele', models.CharField(default='', max_length=10, verbose_name='电话号码')),
                ('adress', models.CharField(default='', max_length=40, verbose_name='地址')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '个人资料',
                'verbose_name_plural': '个人资料',
            },
        ),
        migrations.AddField(
            model_name='userapply',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skyuser.UserInfo', verbose_name='用户名'),
        ),
    ]
