# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('skyuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datalist',
            options={'verbose_name': 'CSS数据', 'verbose_name_plural': 'CSS数据'},
        ),
        migrations.AlterModelOptions(
            name='userapply',
            options={'verbose_name': '数据申请', 'verbose_name_plural': '数据申请'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '个人资料', 'verbose_name_plural': '个人资料'},
        ),
        migrations.AddField(
            model_name='datalist',
            name='apply_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='up_data', verbose_name='申请表'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datalist',
            name='data_year',
            field=models.CharField(default='', max_length=40, verbose_name='数据名称'),
        ),
        migrations.AlterField(
            model_name='userapply',
            name='apply_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='申请时间'),
        ),
        migrations.AlterField(
            model_name='userapply',
            name='certificate',
            field=models.FileField(upload_to='up_apply', verbose_name='上传申请表'),
        ),
        migrations.AlterField(
            model_name='userapply',
            name='data_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skyuser.DataList'),
        ),
        migrations.AlterField(
            model_name='userapply',
            name='result',
            field=models.CharField(choices=[('未审核', '未审核'), ('审核中', '审核中'), ('审核通过', '审核通过'), ('审核未通过', '审核未通过')], default='未审核', max_length=10, verbose_name='申请结果'),
        ),
    ]
