# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 14:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skyuser', '0003_auto_20171118_1912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datalist',
            options={'verbose_name': 'CSS数据管理', 'verbose_name_plural': 'CSS数据管理'},
        ),
        migrations.AlterField(
            model_name='datalist',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='userapply',
            name='data_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skyuser.DataList', verbose_name='数据名称'),
        ),
        migrations.AlterField(
            model_name='userapply',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
    ]
