# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyuser', '0005_auto_20171118_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalist',
            name='apply_file',
            field=models.FileField(blank=True, null=True, upload_to='static/media/up_data', verbose_name='申请表'),
        ),
        migrations.AlterField(
            model_name='datalist',
            name='data_file1',
            field=models.FileField(blank=True, null=True, upload_to='static/media/up_data', verbose_name='数据附件1'),
        ),
        migrations.AlterField(
            model_name='datalist',
            name='data_file2',
            field=models.FileField(blank=True, null=True, upload_to='static/media/up_data', verbose_name='数据附件2'),
        ),
        migrations.AlterField(
            model_name='datalist',
            name='data_file3',
            field=models.FileField(blank=True, null=True, upload_to='static/media/up_data', verbose_name='数据附件3'),
        ),
        migrations.AlterField(
            model_name='userapply',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='static/media/up_apply', verbose_name='上传申请表'),
        ),
    ]
