# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skyuser', '0006_auto_20171118_2307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datalist',
            options={'verbose_name': 'CSS数据', 'verbose_name_plural': 'CSS数据'},
        ),
        migrations.AlterField(
            model_name='datalist',
            name='apply_file',
            field=models.FileField(blank=True, null=True, upload_to='up_data/%Y/%m', verbose_name='申请表'),
        ),
        migrations.AlterField(
            model_name='datalist',
            name='data_file1',
            field=models.FileField(blank=True, null=True, upload_to='up_data/%Y/%m', verbose_name='数据附件1'),
        ),
        migrations.AlterField(
            model_name='datalist',
            name='data_file2',
            field=models.FileField(blank=True, null=True, upload_to='up_data/%Y/%m', verbose_name='数据附件2'),
        ),
        migrations.AlterField(
            model_name='datalist',
            name='data_file3',
            field=models.FileField(blank=True, null=True, upload_to='up_data/%Y/%m', verbose_name='数据附件3'),
        ),
        migrations.AlterField(
            model_name='userapply',
            name='apply_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='申请时间'),
        ),
        migrations.AlterField(
            model_name='userapply',
            name='certificate',
            field=models.FileField(default='', upload_to='up_apply', verbose_name='上传申请表'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userapply',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skyuser.UserInfo', verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='tele',
            field=models.CharField(default='', max_length=11, verbose_name='电话号码'),
        ),
    ]
